# Generated by Django 3.0.4 on 2020-03-27 14:30

from django.db import migrations, models
import example_app.image_patterns
import example_app.models
import image_pattern.contrib.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Text for snippet image')),
                ('image_with_custom_methods', image_pattern.contrib.django.ImagePatternField(blank=True, context=example_app.models.ExampleModel.get_image_pattern_context, null=True, pattern=example_app.image_patterns.ImagePattern, should_be_created=example_app.models.ExampleModel.image_pattern_should_be_created, upload_to='', verbose_name='Фотография')),
                ('image', image_pattern.contrib.django.ImagePatternField(blank=True, context=None, null=True, pattern=example_app.image_patterns.ImagePattern, should_be_created=None, upload_to='', verbose_name='Фотография')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], max_length=20)),
            ],
            options={
                'verbose_name': 'example object',
                'verbose_name_plural': 'example objects',
            },
        ),
    ]
